version: '3.7'
services:

  backend:
    build: app
    ports:
      - '8000'
    volumes:
      - .:/deploy
    working_dir: /deploy/app
    stdin_open: true
    tty: true
    # command: ["/bin/bash"]
    networks:
      - backnet

  proxy:
    build: proxy
    restart: always
    depends_on:
      - backend
    volumes:
      - ./collectstatic:/collectstatic
    ports:
      - 80:80
    extra_hosts:
      private-files.internal: 127.0.0.1
    networks:
      - backnet
      - nginx-gateway

networks:
  backnet:
  nginx-gateway: