version: '3.7'
services:

  backend:
    build: app
    ports:
      - '8000'
    volumes:
      - .:/deploy
    working_dir: /deploy/app
    stdin_open: true
    tty: true
    # command: ["/bin/bash"]
    networks:
      - backnet

  proxy:
    build: proxy
    restart: always
    depends_on:
      - backend
    environment:
      # these variables will be used by the global nginx proxy
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
      VIRTUAL_HOST_ALIAS: "${VIRTUAL_HOST_ALIAS}"
      LETSENCRYPT_HOST: "${LETSENCRYPT_HOST}"
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
    volumes:
      - ./collectstatic:/collectstatic
    ports:
      - "${APP_HOST_PORT}80"
    extra_hosts:
      private-files.internal: 127.0.0.1
    networks:
      - backnet
      - nginx-global-gateway

networks:
  backnet:
  nginx-global-gateway: